[2021-06-21 00:32:50 +0800] [ERROR] 查询Test出错
[错误原因]:(pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'localhost'")
(Background on this error at: http://sqlalche.me/e/14/e3q8)
[错误堆栈]: [\helpers\mysql_helper.py] [line:72] [code]: res = await session.execute(select(Test).where(Test.id != filter_id))
----------------------------------------

[2021-06-21 00:32:50 +0800] [ERROR] 查询失败,没有返回结果
[错误原因]:
[错误堆栈]: [\views\test_view.py] [line:33] [code]: assert db_result and es_result
----------------------------------------

[2021-06-21 00:32:50 +0800] [ERROR] 访问路由</test>失败, 请求方式:POST,请求参数:b'{"test": "1"}'
[响应原文]:b'{"description": "Internal Server Error", "status": 500, "message": "The server encountered an internal error and cannot complete your request."}'
----------------------------------------

[2021-06-21 00:33:31 +0800] [ERROR] 查询Test出错
[错误原因]:(pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'localhost'")
(Background on this error at: http://sqlalche.me/e/14/e3q8)
[错误堆栈]: [\helpers\mysql_helper.py] [line:72] [code]: res = await session.execute(select(Test).where(Test.id != filter_id))
----------------------------------------

[2021-06-21 00:33:31 +0800] [ERROR] 查询失败,没有返回结果
[错误原因]:
[错误堆栈]: [\views\test_view.py] [line:34] [code]: assert db_result and es_result
----------------------------------------

[2021-06-21 00:33:31 +0800] [ERROR] 访问路由</test>失败, 请求方式:POST,请求参数:b'{"test": "1"}'
[响应原文]:b'{"description": "Internal Server Error", "status": 500, "message": "The server encountered an internal error and cannot complete your request."}'
----------------------------------------

[2021-06-21 00:34:30 +0800] [ERROR] 查询Test出错
[错误原因]:(pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '192.168.3.128'")
(Background on this error at: http://sqlalche.me/e/14/e3q8)
[错误堆栈]: [\helpers\mysql_helper.py] [line:72] [code]: res = await session.execute(select(Test).where(Test.id != filter_id))
----------------------------------------

[2021-06-21 00:34:30 +0800] [ERROR] 查询失败,没有返回结果
[错误原因]:
[错误堆栈]: [\views\test_view.py] [line:34] [code]: assert db_result and es_result
----------------------------------------

[2021-06-21 00:34:30 +0800] [ERROR] 访问路由</test>失败, 请求方式:POST,请求参数:b'{"test": "1"}'
[响应原文]:b'{"description": "Internal Server Error", "status": 500, "message": "The server encountered an internal error and cannot complete your request."}'
----------------------------------------

